### ISSUE TITLE
2016/09/24以降のGenisysでエラーが発生してしまいます

### ISSUE THREAD

**Issue by Kuri0421** [PMMP-JPN/KillBearBoys#1]
`Notice: Undefined property: pocketmine\Player::$loginData in　phar://Z:XXXXXXX/plugins/KillBearBoyshk_v3.0.0.phar/src/KillBearBoys/KillBearBoys.php on line 103`

**Comment by haniokasai** [comment]
$player->loginData["clientId"]; 
という文を
$player->getClientId();

としてみて、確認してください
